
// Generated by Cadence Genus(TM) Synthesis Solution 16.22-s033_1
// Generated on: Jan 17 2020 11:33:08 EST (Jan 17 2020 16:33:08 UTC)

// Verification Directory fv/c17 

module c17(N1, N2, N3, N6, N7, N22, N23);
  input N1, N2, N3, N6, N7;
  output N22, N23;
  wire N1, N2, N3, N6, N7;
  wire N22, N23;
  wire N10, N11, N16, N19;
  nand NAND2_1 (N10, N1, N3);
  nand NAND2_2 (N11, N3, N6);
  nand NAND2_3 (N16, N2, N11);
  nand NAND2_4 (N19, N11, N7);
  nand NAND2_5 (N22, N10, N16);
  nand NAND2_6 (N23, N16, N19);

  // __INJECTED_FAULT__ range=100-500 type=glitch id=1 net=N6 delays=(7,9)
  initial begin
    #7 N6 = ~N6;
    #2 N6 = ~N6;
  end
  // __INJECTED_FAULT__ range=100-500 type=glitch id=2 net=N3 delays=(20,29)
  initial begin
    #20 N3 = ~N3;
    #9 N3 = ~N3;
  end
  // __INJECTED_FAULT__ range=100-500 type=glitch id=3 net=N10 delays=(4,9)
  initial begin
    #4 N10 = ~N10;
    #5 N10 = ~N10;
  end
  // __INJECTED_FAULT__ range=100-500 type=glitch id=4 net=N22 delays=(10,12)
  initial begin
    #10 N22 = ~N22;
    #2 N22 = ~N22;
  end
  // __INJECTED_FAULT__ range=100-500 type=glitch id=5 net=N1 delays=(12,19)
  initial begin
    #12 N1 = ~N1;
    #7 N1 = ~N1;
  end
  // __INJECTED_FAULT__ range=100-500 type=glitch id=6 net=N23 delays=(13,18)
  initial begin
    #13 N23 = ~N23;
    #5 N23 = ~N23;
  end
  // __INJECTED_FAULT__ range=100-500 type=glitch id=7 net=N11 delays=(4,13)
  initial begin
    #4 N11 = ~N11;
    #9 N11 = ~N11;
  end
  // __INJECTED_FAULT__ range=100-500 type=glitch id=8 net=N19 delays=(12,21)
  initial begin
    #12 N19 = ~N19;
    #9 N19 = ~N19;
  end
  // __INJECTED_FAULT__ range=100-500 type=glitch id=9 net=N7 delays=(9,10)
  initial begin
    #9 N7 = ~N7;
    #1 N7 = ~N7;
  end
  // __INJECTED_FAULT__ range=100-500 type=glitch id=10 net=N2 delays=(14,24)
  initial begin
    #14 N2 = ~N2;
    #10 N2 = ~N2;
  end
  // __INJECTED_FAULT__ range=100-500 type=glitch id=11 net=N16 delays=(20,27)
  initial begin
    #20 N16 = ~N16;
    #7 N16 = ~N16;
  end
endmodule

